### ISSUE TITLE
No extra vars field when MySQL selected

### ISSUE THREAD

**Issue by vitaleg** [cyborgbackup/cyborgbackup-ui#11]
According to documentation https://cyborgbackup.readthedocs.io/en/latest/user/quickstart.html#object-relation
i should set extra vars for MySQL backup, but when i select "MySQL" in Policy form, field extra vars just disappears.

Screenshots:
https://i.imgur.com/qJPHZVl.png
https://i.imgur.com/5q2gWBk.png

**Comment by GaetanF** [comment]
Hello,

This part of configuration have been moved on the client element. You must add a client on the policy and you will have an extra button on the client to select the wanted database.

Regards,
