### ISSUE TITLE
Fresh install : unable to login

### ISSUE THREAD

**Issue by Floche87** [cyborgbackup/cyborgbackup-ui#2]
Hi,
I'm unable to connect to cyberborgbackup after fresh install.
I have followed the guide available on readthedocs.io (docker section).
I use admin@cyborg.local to login. 

In debug tool (firefox), i have this issue :
ERROR TypeError: /name="csrfmiddlewaretoken" value="([0-9a-zA-Z]+)"/.exec(...) is null
    authenticate djangopassword-strategy.ts:182
    RxJS 9
        __tryOrUnsub
        next
        _next
        next
        _next
        next
        notifyNext
        _next
        next
    Angular 8
        onLoad
        invokeTask
        onInvokeTask
        invokeTask
        runTask
        invokeTask
        invokeTask
        globalZoneAwareCallback
core.js:4127
    Angular 4
    RxJS 5
    Angular 11

Thx

**Comment by GaetanF** [comment]
Hello,

Did you have access to the API backend ? Normally under /api/v1 url.

Regards

**Comment by Floche87** [comment]
When i try http://localhost:8088/api/v1, i just return to http://localhost:8088

**Comment by GaetanF** [comment]
Hello,

Ok, so you need to specify the http://localhost:8000 on the Specific Server Field on the login form.

Regards

**Comment by Floche87** [comment]
great it works
Thanks

**Comment by Floche87** [comment]
great it works
thanks
